### ISSUE TITLE
[UI] As a user,  I can sign in with email and password

### ISSUE THREAD

**Issue by nkhanh44** [nkhanh44/ic-survey-ios#4]
## Why

- Users must be authenticated before taking or viewing any surveys.

- The mobile apps should allow users to authenticate with their email and password. 

## Acceptance Criteria?
- Display the Nimble logo
- Display the blurred background
- Display the Email text input
  - Set the placeholder text to `Email`
- Display the Password text input
  - Set the placeholder text to `Password`

- Display the Login button
**DO NOT** _display the Forgot Password button yet. We will work on this on another separate epic._

## Design
![Screen Shot 2022-07-21 at 11 16 20](https://user-images.githubusercontent.com/25881847/180128985-b025119e-131b-4c1b-86a5-b8b6c13de1c2.png)

**Comment by blyscuit** [comment]
Would be better if you list the components that have to be included in this issue in point form, for example:
- email textfield
- background picture
- button

**Comment by blyscuit** [comment]
Optional: After you come up with the components it might be worth to separate the issue to smaller ones for each of the components if they are too big of a PR. 👍

**Comment by nkhanh44** [comment]
Thank you, Bliss. I will update issues and apply them for the rest as well 👍 .
